import { defineConfig, devices } from '@playwright/test';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const BASE_URL = process.env.PW_BASE_URL ?? 'http://localhost:8080';

/**
 * Auth storage state files (generated by auth.setup.ts)
 * One per user role — reused across all specs.
 */
export const STORAGE_STATES = {
  selfStudent: path.resolve(__dirname, '../.auth/self-student.json'),
  enrolledStudent: path.resolve(__dirname, '../.auth/enrolled-student.json'),
  teacher: path.resolve(__dirname, '../.auth/teacher.json'),
  institution: path.resolve(__dirname, '../.auth/institution.json'),
};

export default defineConfig({
  testDir: '.',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 2 : undefined,
  timeout: 30_000,

  // Starts the frontend dev server if not already running at BASE_URL.
  // reuseExistingServer:true means "if localhost:8080 is up, use it; else run the command".
  webServer: {
    command: 'npm --prefix ../Frontend run dev',
    url: BASE_URL,
    reuseExistingServer: true,
    timeout: 120_000,
    stdout: 'ignore',
    stderr: 'pipe',
  },

  reporter: [
    ['html', { outputFolder: '../playwright-report' }],
    ['allure-playwright', { outputFolder: '../allure-results' }],
    ['list'],
  ],

  use: {
    baseURL: BASE_URL,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'on-first-retry',
    // Route all API calls through MSW stubs when STUB_MODE=true
    serviceWorkers: process.env.STUB_MODE === 'true' ? 'allow' : 'block',
  },

  projects: [
    // ── Auth setup (must run first) ──────────────────────────────────────
    {
      name: 'auth-setup',
      testMatch: /auth\/auth\.setup\.ts/,
    },

    // ── Self-enrolled student ────────────────────────────────────────────
    {
      name: 'student-self',
      testMatch: /student-self-enrolled\/.+\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        storageState: STORAGE_STATES.selfStudent,
      },
      dependencies: ['auth-setup'],
    },

    // ── Teacher-enrolled student ─────────────────────────────────────────
    {
      name: 'student-enrolled',
      testMatch: /student-teacher-enrolled\/.+\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        storageState: STORAGE_STATES.enrolledStudent,
      },
      dependencies: ['auth-setup'],
    },

    // ── Teacher ──────────────────────────────────────────────────────────
    {
      name: 'teacher',
      testMatch: /teacher\/.+\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        storageState: STORAGE_STATES.teacher,
      },
      dependencies: ['auth-setup'],
    },

    // ── Institution ──────────────────────────────────────────────────────
    {
      name: 'institution',
      testMatch: /institution\/.+\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        storageState: STORAGE_STATES.institution,
      },
      dependencies: ['auth-setup'],
    },

    // ── Auth flows (no pre-auth state) ───────────────────────────────────
    {
      name: 'auth-flows',
      testMatch: /auth\/(?!auth\.setup).*\.spec\.ts/,
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
